# Application properties for Spring Cache demo
spring.main.banner-mode=off
server.port=8081

# Note: Caching configurations (Default, Caffeine, Redis)
# H2 Database configuration
spring.datasource.url=jdbc:h2:mem:cachedb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Hibernate settings
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# springdoc (Swagger) settings
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html


spring.cache.type=redis
#mak.redis.cache.enabled=true